apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-mk
  generation: 1
  labels:
    io.kompose.service: check-mk
spec:
  replicas: 1
  selector:
      matchLabels:
        io.kompose.service: check-mk
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      labels:
        io.kompose.service: check-mk
    spec:
      containers:
      - name: check-mk
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 6
          successThreshold: 1
          tcpSocket:
            port: 5000
          timeoutSeconds: 6
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 6
          successThreshold: 1
          tcpSocket:
            port: 5000
          timeoutSeconds: 6
        volumeMounts:
        - mountPath: /home/mgeweb/monitoring/check_mk
          name: volume-check-mk
          subPath: {{ .Release.Namespace }}/omd/sites
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      volumes:
        - name: volume-check-mk
          persistentVolumeClaim:
            claimName: volume-check-mk
status: {}
