{{- if .Values.loadBalancer.enabled  }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  name: ingress
spec:
  rules:
  - host: {{ .Values.loadBalancer.dns }}
    http:
      paths:
      - backend:
          serviceName: check-mk
          servicePort: 5000
status:
  loadBalancer: {}
{{- end }}
