apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sankhya-w
  name: sankhya-w
spec:
  ports:
  - name: "9990"
    port: 9990
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: sankhya-w
status:
  loadBalancer: {}
