apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sas
  name: sas
spec:
  ports:
  - name: "10050"
    port: 10050
    protocol: TCP
    targetPort: 10050
  selector:
    io.kompose.service: sas
status:
  loadBalancer: {}