{{- if .Values.datasync.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: datasync
  labels:
    io.kompose.service: datasync
spec:
  ports:
  - name: "9980"
    port: 9980
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: datasync
status:
  loadBalancer: {}
{{- end }}