apiVersion: v1
kind: Secret
metadata: 
  name: jiva-w
type: Opaque
data:
  banco-password: "{{ .Values.banco.senha | b64enc }}"
  banco-user: "{{ .Values.banco.usuario | b64enc  }}"
  banco-ip: "{{ .Values.banco.ip | b64enc }}"